GHA: Fix dynamic script filename
When re-using this github-actions workflow from other repositories, the yaml
filename (with extension) or a manually specified workflow name may be passed
in.  This may not match the script filename from the podman repository.  Since
the script will never have a different filename, fix this by hard-coding it.

This resolves errors like:

```
Run
./_podman/.github/actions/.github/workflows/check_cirrus_cron.yml/cron_failures.sh
  ./_podman/.github/actions/.github/workflows/check_cirrus_cron.yml/cron_failures.sh
  shell: /usr/bin/bash -e {0}
  env:
    RCPTCSV: rh.container.bot@gmail.com,podman-monitor@lists.podman.io
    NAME_ID_FILEPATH: ./artifacts/name_id.txt
/home/runner/work/_temp/a4b017c4-7dac-473e-8b3d-a7373ed0156b.sh: line 1:
./_podman/.github/actions/.github/workflows/check_cirrus_cron.yml/cron_failures.sh:
No such file or directory
Error: Process completed with exit code 127.
```

i.e. `${{ github.workflow }}` resolved to `check_cirrus_cron.yml`
instead of the expected `check_cirrus_cron` by the workflow.

Signed-off-by: Chris Evich <cevich@redhat.com>